server:
  port: 8081

app:
  env: local

spring:
  application:
    name: kafka-streams

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      max-poll-records: 1

    producer:
      properties:
        spring.json.add.type.headers: false

    streams:
      application-id: ${app.env}-${spring.application.name}

  cloud:
    stream:
      bindings:
        loja-novo-pedido-in-0:
          useNativeDecoding: true
          destination: LOJA_NOVO_PEDIDO
        loja-novo-pedido-out-0:
          useNativeDecoding: true
          destination: LOJA_NOVO_PEDIDO_RESULTADO
      function:
        definition: loja-novo-pedido

    kafka:
      binder:
        autoCreateTopics: true